// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WorkShop1_WebApp.Models;

#nullable disable

namespace WorkShop1_WebApp.Migrations
{
    [DbContext(typeof(StoreDbContext))]
    [Migration("20230609161303_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WorkShop1_WebApp.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "LapTop",
                            Description = "Dell_V110 tetsttsttstst",
                            Name = "Dell_V110",
                            Price = 100
                        },
                        new
                        {
                            Id = 2,
                            Category = "LapTop",
                            Description = "Acer_V110 tetsttsttstst",
                            Name = "Acer_V110",
                            Price = 522
                        },
                        new
                        {
                            Id = 3,
                            Category = "LapTop",
                            Description = "Toshiba_V110 tetsttsttstst",
                            Name = "Toshiba_V110",
                            Price = 500
                        },
                        new
                        {
                            Id = 4,
                            Category = "Computer",
                            Description = "tetsttsttstst",
                            Name = "AllInOne_V110",
                            Price = 800
                        },
                        new
                        {
                            Id = 5,
                            Category = "Computer",
                            Description = "tetsttsttstst",
                            Name = "Dell_V110",
                            Price = 600
                        },
                        new
                        {
                            Id = 6,
                            Category = "Mobile",
                            Description = "tetsttsttstst",
                            Name = "Iphone_V110",
                            Price = 500
                        },
                        new
                        {
                            Id = 7,
                            Category = "Mobile",
                            Description = "tetsttsttstst",
                            Name = "Sumsung_V110",
                            Price = 750
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
